name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup GHDL
      # You may pin to the exact commit or the version.
      # uses: ghdl/setup-ghdl-ci@d178472c1018df2b5cb401b5f22c6b1fd94b0da7
      uses: ghdl/setup-ghdl-ci@nightly
      with:
        # Select GHDL backend (mcode, llvm or gcc)
        backend: gcc
          
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
          
    - name: Pip Installer
      # You may pin to the exact commit or the version.
      # uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
      uses: BSFishy/pip-action@v1
      with:
        # The packages to install from Pip
        packages: cocotb numpy
        
    - name: run sim
      run: make
